version: '3'

services:
  app:
    container_name: nextjs-app
    image: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db